# Generated by Django 3.0.7 on 2020-06-20 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memesahaab', '0003_auto_20200618_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memesahaab.Meme')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
