# Generated by Django 3.0.7 on 2020-07-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memesahaab', '0005_auto_20200620_2319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
