# Generated by Django 3.0.7 on 2020-07-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memesahaab', '0008_auto_20200706_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catg_meme',
            name='catg_meme',
            field=models.ImageField(default=1, upload_to='memes/catgs'),
            preserve_default=False,
        ),
    ]
