# Generated by Django 3.0.7 on 2020-07-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memesahaab', '0009_auto_20200706_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='catg_meme',
            name='caption',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catg_meme',
            name='meme_file',
            field=models.FileField(default=1, upload_to='memes/catg_files'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catg_meme',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='catg_meme',
            name='catg_meme',
            field=models.ImageField(blank=True, null=True, upload_to='memes/catgs'),
        ),
    ]
