# Generated by Django 3.0.7 on 2020-07-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memesahaab', '0010_auto_20200706_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catg_meme',
            name='catg_meme',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded.html'),
        ),
        migrations.AlterField(
            model_name='catg_meme',
            name='meme_file',
            field=models.FileField(upload_to='uploaded.html'),
        ),
    ]
