# Generated by Django 3.0.7 on 2020-07-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memesahaab', '0012_loss_meme'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeMan_Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('caption', models.TextField()),
                ('mememan_meme', models.ImageField(blank=True, null=True, upload_to='uploaded.html')),
                ('mememan_meme_file', models.FileField(upload_to='uploaded.html')),
            ],
        ),
        migrations.CreateModel(
            name='Surreal_Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('caption', models.TextField()),
                ('surreal_meme', models.ImageField(blank=True, null=True, upload_to='uploaded.html')),
                ('surreal_meme_file', models.FileField(upload_to='uploaded.html')),
            ],
        ),
    ]
