# Generated by Django 3.0.7 on 2020-07-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memesahaab', '0014_auto_20200710_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loss_meme',
            name='loss_meme_file',
        ),
        migrations.RemoveField(
            model_name='mememan_meme',
            name='mememan_meme_file',
        ),
        migrations.RemoveField(
            model_name='surreal_meme',
            name='surreal_meme_file',
        ),
    ]
