# Generated by Django 3.0.7 on 2020-07-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memesahaab', '0015_auto_20200711_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loss_meme',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loss_meme',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loss_meme',
            name='loss_meme_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loss_meme',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mememan_meme',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mememan_meme',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mememan_meme',
            name='mememan_meme_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mememan_meme',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='surreal_meme',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='surreal_meme',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surreal_meme',
            name='surreal_meme_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surreal_meme',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
