# Generated by Django 3.0.7 on 2020-07-11 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memesahaab', '0016_auto_20200711_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='meme_loss',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='memesahaab.Loss_Meme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='meme_mememan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='memesahaab.MemeMan_Meme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='meme_surreal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='memesahaab.Surreal_Meme'),
            preserve_default=False,
        ),
    ]
